import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const res = await fetch(
    'https://worldtimeapi.org/api/timezone/Australia/Brisbane',
    {
      next: {
        revalidate: 5,
      },
    }
  )
  const data = await res.json()
  return (
    <html lang='en'>
      <body>
        <h1>{data.datetime}</h1>
        {children}
      </body>
    </html>
  )
}
